# Используем образ Nginx
FROM nginx:alpine
# Копируем содержимое текущего каталога в контейнер в /usr/share/nginx/html
COPY . /usr/share/nginx/html
# Указываем порт, который будет использоваться в контейнере
EXPOSE 80